version: '3.1'

services:
  webui:
    image: "web-ui"
    restart: always 
    ports:
      - 3000:3000
    networks:
    - dataspacesnw  
    
networks:
  dataspacesnw:
    external: true